/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governance from "./governance";
export type { governance };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { FundFactory } from "./FundFactory";
export type { YieldFundAAVE } from "./YieldFundAAVE";
