/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FundFactory } from "./FundFactory";
export type { PromiseFundFactory } from "./PromiseFundFactory";
