/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PromiseFund__factory } from "./PromiseFund__factory";
export { PromseFund__factory } from "./PromseFund__factory";
