/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFund__factory } from "./IFund__factory";
export { IYieldFund__factory } from "./IYieldFund__factory";
